### PR TITLE
My FlickrMirrorer features

### PR DESCRIPTION
**Pull request by ciprian-radu**
Please consider my contribution to FlickrMirrorer for merging. It includes a few features that I found useful while trying to use FlickrMirrorer with my fairly large Flickr photostream.

I'm not a Python developer so please review the code and improve it if necessary.

### CODE REVIEW

**Comment by markdoliner** [comment]
Thanks, Ciprian. I'm starting to look at this now. Question for you: Are there advantages to putting the API key and secret in a separate file? One disadvantage is that it's a little more complicated for a user to move/install the script somewhere (the user must remember to also copy the config file). Are there situations where the key and secret need to be changed? Did you need to change them?

**Comment by ciprian-radu** [comment]
I use my own Flickr app to pull my photos. Everybody should change this setting because one should not trust personal content with a Flickr app that everybody could use. Does this make sense?

**Comment by markdoliner** [comment]
> Does this make sense?

Yes, it makes sense. And I initially had the same concern. But I do not believe the Flickr API actually works that way. I believe the API key and secret are used to obtain an access token via oauth, which requires that the user agree to allow Flickr Mirror read access to the user's photostream. The python flickrapi library saves the access token in ~/.flickr/. I believe Flickr grants read permissions only to this specific access token--not to anyone using the same API key and secret.

I tested this again just now and I believe it's safe. Here's what I did:
1. Change `user_id='me'` to `user_id='markdoliner'` in the API call in flickrmirror.py
2. Using a separate user account on my local computer, run the flickrmirror.py script.
3. When the browser opens, log into Yahoo using a different Yahoo account (not 'markdoliner'). Grant access. Paste the code in the terminal window.
4. Confirm that markdoliner's private photos are not downloaded.

So I _believe_ it's safe for everyone to use the same API key and secret. But if I'm wrong, someone please let me know! If that's the case I would want to invalidate the current secret, stop distributing it, and include instructions on how people can register for their own key and secret.

**Comment by simonneutert** [comment]
IMHO you are correct, Mark. The keys are based for the App itself, not a particular user. So the setup should be good as it is - making it much easier for inexperienced programmers/users.

Taken from [Flickr Docs: API Keys](https://www.flickr.com/services/api/misc.api_keys.html):

> API Keys
> 
> To use the Flickr API you need to have an application key. We use this to track API usage.
> 
> Currently, commercial use of the API is allowed only with prior permission. Requests for API keys intended for commercial use are reviewed by staff. If your project is personal, artistic, free or otherwise non-commercial please don't request a commercial key. If your project is commercial, please provide sufficient detail to help us decide. Thanks!

**Comment by markdoliner** [comment]
FYI I'm working on cherry-picking these changes in. I think that will end up with a cleaner commit history than merge the pull request outright. I've merged in your changes for --ignore-photos and --ignore-videos and printing statistics on SIGINT. Working on the remaining changes now. I have an idea about how to clean up some of the manual video download code.

No need for you to change anything--just wanted to give you a status update.

**Comment by ciprian-radu** [comment]
Maybe Flickr does not show user sensitive information to the application owner. It looks like it shows only a user count and some overall stats. Still an app secret should remain secret. Moreover, others use a similar approach. See https://stuvel.eu/flickrapi-doc/3-auth.html
Also, this is a CLI app. I'm sure the users can handle a config file, which by default uses your Flickr app.

**Comment by markdoliner** [comment]
Ok, I've pushed some changes. Due to resolving merge conflicts when cherry-picking, I believe my git hashes are different from the ones in the pull request so GitHub won't be able to detect which changes have been applied. I'm going to close this particular pull request. Feel free to open others for other features.

The commits that aren't in master are:
- The "save progress" commits. I cherry-picked these and resolved the merge conflicts (which I caused by making other changes to master after you created this pull request). I pushed the commits to my `ciprian-radu_save_and_resume_progress` branch. I have a concern that these changes will cause metadata for old photos not to be updated if the title and description change (also the view count, but that's less important).
- 69307fb "Configure Flickr Mirrorer." I'm still not convinced this is needed. Yes it's called a secret... but I don't believe that being in possession of the secret allows anyone to have special access to anything. I'll try to do more testing in case I'm wrong.

Thanks for all the improvements!

**Comment by simonneutert** [comment]
@markdoliner thank you so much for making the effort!

@ciprian-radu thank you very much for your input. And for making this issues topic much clearer to my future me ;-)

**Pull request closed without merging**
